UrenRegistratieQien/Controllers/MailserviceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailKit;
using MailKit.Net.Smtp;
using MimeKit;
using UrenRegistratieQien.Repositories;
using UrenRegistratieQien.Models;
using UrenRegistratieQien.MailService;
using Microsoft.AspNetCore.Http;
using UrenRegistratieQien.Exceptions;

namespace UrenRegistratieQien.Controllers
{
    public class MailserviceController : Controller
    {
        private readonly IDeclarationFormRepository declarationFormRepo;
        private readonly IEmployeeRepository employeeRepo;

        public MailserviceController(IDeclarationFormRepository DeclarationFormRepo, IEmployeeRepository EmployeeRepo)
        {
            declarationFormRepo = DeclarationFormRepo;
            employeeRepo = EmployeeRepo;
        }

        [HttpPost]
        public async Task<IActionResult> MailService(DeclarationFormModel decModel, string uniqueId, string formId, string employeeName, IFormFile file)
        {
            employeeRepo.UploadFile(file, decModel.FormId);
            if (!await employeeRepo.UserIsEmployeeOrTrainee())
            {
                return AccessDeniedView();
            }
            
            try
            {
                await declarationFormRepo.EditDeclarationForm(decModel);
            }
            catch (MoreThan24HoursException e)
            {
                return RedirectToAction("HourReg", "DeclarationForm", new { declarationFormId = decModel.FormId, userId = decModel.EmployeeId, year = decModel.Year, month = decModel.Month, errorMessage = e.Message });
            }

            await declarationFormRepo.SubmitDeclarationForm(decModel);
            await declarationFormRepo.CalculateTotalHours(decModel);

            //hier word mail opgesteld en verstuurd
            Mailservice.MailFormToClient(decModel, uniqueId, formId, employeeName);
            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }

        public async Task<IActionResult> ApproveOrReject(string uniqueId, string formId, bool commentNotValid)
        {
            var formIdAsInt = Convert.ToInt32(formId);

            if (await declarationFormRepo.CheckIfIdMatches(uniqueId))
            {
                var declarationFormModel = await declarationFormRepo.GetForm(formIdAsInt);
                return View(new RejectFormModel { declarationFormModel = declarationFormModel, commentNotValid = commentNotValid });
            }
            else
            {
                return View("~/Views/Mailservice/ErrorUnknownId.cshtml");
            }
        }


        [HttpPost]
        public async Task<IActionResult> Approve(string formId)
        {
            await declarationFormRepo.ApproveForm(Convert.ToInt32(formId));
            return View();
        }

        public async Task<IActionResult> ApproveMailChange(string newMail, string oldMail)
        {
            await employeeRepo.EditEmployeeMail(oldMail, newMail);

            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("Qien", "hanshanshans812@gmail.com"));
            message.To.Add(new MailboxAddress(newMail, newMail));
            message.Subject = "Email wijziging bevestigd door Admin";
            message.Body = new TextPart("html")
            {
                Text = $"Beste,<br>Je e-mailadres wijziging is bevestigd door de Admin. <br> Vanaf nu kan er inlogd worden met: {newMail} <br> Met vriendelijke groet <br> "
            };

            using (var client = new SmtpClient())
            {
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                client.Connect("Smtp.gmail.com", 587, false);
                client.Authenticate("hanshanshans812@gmail.com", "Hans123!"); //
                client.Send(message);
                client.Disconnect(true);
            }

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Reject(int FormId, RejectFormModel rejectFormModel, string employeeName, string clientName)
        {
            var declarationFormModel = await declarationFormRepo.GetForm(FormId);
            var uniqueId = declarationFormModel.uniqueId;
            var comment = rejectFormModel.comment;

            if (ModelState.IsValid)
            {
                await declarationFormRepo.RejectForm(FormId, comment);
                //aanroepen mailservice afkeuren
                Mailservice.RejectMailToAdminAndEmployee(declarationFormModel, employeeName, clientName);
                return View();
            } else
            {
                return RedirectToAction("ApproveOrReject", new { uniqueId = uniqueId, formId = FormId, commentNotValid = true});
            }
        }
        public ViewResult AccessDeniedView()
        {
            return View("~/Views/Home/AccessDenied.cshtml");
        }
    }
}

UrenRegistratieQien/Views/Mailservice/Approve.cshtml
@{
    ViewData["Title"] = "Approve";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />


<h1>Formulier goedgekeurd</h1>

UrenRegistratieQien/Views/Mailservice/ApproveMailChange.cshtml
@{
    ViewData["Title"] = "Approve";
}

<h1>E-mailadres wijziging bevestigd.</h1>
<p>Er is een bevestiging naar de medewerker gestuurd.</p>

UrenRegistratieQien/Views/Mailservice/ApproveOrReject.cshtml
@model RejectFormModel
@{
    ViewData["Title"] = "ApproveOrReject";

}
    <h1 class="title">Urendeclaratieformulier</h1>

<div class="approvereject Container-1">
    <br />
    <br />
    <div class="box-30left">
        <div>
            Medewerker: @Model.declarationFormModel.EmployeeName
            <br />
            Maand: @Model.declarationFormModel.Month

        </div>

        <br />
        Op dit scherm kunt u kiezen of u het urendeclaratieformulier van @Model.declarationFormModel.EmployeeName goedkeurt of afkeurt. Geef bij het afkeuren ook aan waarom het formulier wordt afgekeurd.
    </div>
    <br />
    <div class="box-70right">
        <div class="Container-1">
            <div class="box-5050">
                <form method="post">
                    <button class="btn-primary" asp-action="Approve" asp-controller="Mailservice" asp-route-formId=@Model.declarationFormModel.FormId>Goedkeuren</button>
                </form>
            </div>
            <div class="box-5050">
                <form method="post">

                    <button class="btn-primary" asp-action="Reject" asp-controller="Mailservice" asp-route-formId=@Model.declarationFormModel.FormId asp-route-employeeName="@Model.declarationFormModel.EmployeeName" asp-route-clientName="@Model.declarationFormModel.ClientName">Afkeuren</button>
                    <br />
                    <br />
                    @Html.HiddenFor(p => p.declarationFormModel.FormId)
                    @Html.ValidationMessageFor(p => p.comment)
                    @if (Model.commentNotValid)
                    {
                        <div class="validation-failed">
                            Dit veld is verplicht!
                        </div>
                    }
                    @Html.TextAreaFor(p => p.comment, 5, 40, new { @class = "wide-textbox" })
                    @*@Html.TextBoxFor(p => p.comment, new { @class= "wide-textbox" })*@
                    
                </form>
            </div>
        </div>
        <br />
    </div>
    <br />
    <br />

</div>

<table class="fl-table" align="center">
    <thead>
        <tr>
            <th class="tableHeader">Date</th>
            <th class="tableHeader">Gewerkt</th>
            <th class="tableHeader">Overwerk</th>
            <th class="tableHeader">Ziekte</th>
            <th class="tableHeader">Vakantie</th>
            <th class="tableHeader">Feestdagen</th>
            <th class="tableHeader">Training</th>
            <th class="tableHeader">Overig</th>
            <th>Overig Uitleg</th>
        </tr>
    </thead>

    <tbody>
        @Html.DisplayFor(m => Model.declarationFormModel.HourRows)
    </tbody>
</table>

UrenRegistratieQien/Views/Mailservice/ErrorUnknownId.cshtml
@{
    ViewData["Title"] = "View";
}
<br />
<br />
<br />
<br />
<br />
<br />

<h1>Error: unknown form id. Please contact the administrator.</h1>

UrenRegistratieQien/Views/Mailservice/Reject.cshtml
@{
    ViewData["Title"] = "Reject";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<h1>Formulier afgekeurd</h1>