UrenRegistratieQien/Controllers/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UrenRegistratieQien.GlobalClasses;
using UrenRegistratieQien.Models;
using UrenRegistratieQien.Repositories;

namespace UrenRegistratieQien.Controllers
{
    public class DownloadController : Controller
    {
        private readonly IDeclarationFormRepository declarationFormRepo;

        public DownloadController(IDeclarationFormRepository declarationFormRepo)
        {
            this.declarationFormRepo = declarationFormRepo;
        }


        public async Task<FileContentResult> DownloadExcel(int formId)
        {
            Download download = new Download();
            DeclarationFormModel declarationForm = await declarationFormRepo.GetForm(formId);

            download.MakeExcel(Convert.ToString(formId), declarationForm.HourRows);
            var fileName = Convert.ToString(formId) + ".xlsx";

            byte[] fileBytes = System.IO.File.ReadAllBytes("Downloads/" + fileName);
            return File(fileBytes, "Application/x-msexcel", fileName);
        }


        public ActionResult DownloadAttachments(int formId)
        {
            var fileName = $"{formId}.zip";
            var zipFilePath = "wwwroot/Uploads/" + fileName;
            if (System.IO.File.Exists(zipFilePath))
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(zipFilePath);
                return File(fileBytes, "application/zip", fileName);
            }
            return RedirectToAction("admin", "admin");
        }

        public FileContentResult DownloadTotalHoursCSV(int totalWorked, int totalOvertime, int totalSickness, int totalVacation, int totalHoliday, int totalTraining, int totalOther) //eventueel filters meenemen..
        {
            List<string> downloadableList = new List<string>
            {
                Convert.ToString(totalWorked),
                Convert.ToString(totalOvertime),
                Convert.ToString(totalSickness),
                Convert.ToString(totalVacation),
                Convert.ToString(totalHoliday),
                Convert.ToString(totalTraining),
                Convert.ToString(totalOther)
            };
            Download download = new Download();
            string fileName = "Totalhours.txt";
            string header = "gewerkt, overuren, ziekte, vakantie, feestdagen, training, anders";
            download.MakeCSV(header, downloadableList, fileName);

            byte[] fileBytes = System.IO.File.ReadAllBytes("Downloads/" + fileName);
            return File(fileBytes, "text/plain", fileName);
        }
    }
}

UrenRegistratieQien/Views/Admin/AddClient.cshtml
@model UrenRegistratieQien.Models.ClientModel

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>


    <div class="box-2">
        <form asp-controller="Admin" asp-action="AddClient">
            @Html.HiddenFor(m => m.ClientId)
            <table class="fl-table table-wrapper three" align="center">
                <thead>
                    <tr>
                        <th class="textleft">Gegevens</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.CompanyName)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.CompanyName)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.CompanyPhone)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.CompanyPhone)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact1Name)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact1Name)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact1Phone)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact1Phone)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact1Email)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact1Email)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact2Name)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact2Name)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact2Phone)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact2Phone)</td>
                    </tr>
                    <tr>
                        <td class="textleft">@Html.LabelFor(m => m.Contact2Email)</td>
                        <td class="textleft">@Html.TextBoxFor(m => m.Contact2Email)</td>
                    </tr>
                </tbody>
            </table>
            <div class="btnCenter"><button type="submit" class="btn-primary btn btnCenter">Toevoegen</button></div>
        </form>
    </div>
</div>

UrenRegistratieQien/Views/Admin/Admin.cshtml
@using UrenRegistratieQien.Models
@using System.Collections.Generic
@model List<DeclarationFormModel>

@{
    ViewData["Title"] = "Dashboard Admin";

    var employeeNames = new List<string>();

    foreach (DeclarationFormModel declarationFormModel in ViewBag.AllForms)

    {
        if (!employeeNames.Contains(declarationFormModel.EmployeeName))
        {
            employeeNames.Add(declarationFormModel.EmployeeName);
        }
    }
    string currentYear = Convert.ToString(DateTime.Now.Year);
    int currentYearInt = Convert.ToInt32(currentYear);

    var years = new List<int>();
    foreach (DeclarationFormModel declarationFormModel in ViewBag.AllForms)
    {
        if (!years.Contains(declarationFormModel.Year))
        {
            years.Add(declarationFormModel.Year);
        }
    }

    years.Sort();
    var yearsSelectList = new SelectList(years);
    foreach(var x in yearsSelectList)
    {
        if(x.Text == currentYear)
        {
            x.Selected = true;
        }
    }

    var stringAscending = "Ascending";
    var stringDescending = "Descending";
    var totalHours = (TotalsModel)ViewBag.TotalHours;
}


<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">
        <div align="center">
            <h1>Totaaloverzicht</h1>
        </div>
        </td>
        <div>
            @using (Html.BeginForm("Admin", "Admin"))
            {
            <input class="btn-primary btn btnposition" type="image" alt="filter toepassen" src="..\..\Images\Filter_Icon_White_Small.png" title="filter toepassen" />
                <button class="btn-primary btn btnposition"
                        asp-controller="Download"
                        asp-action="DownloadTotalHoursCSV"
                        asp-route-totals=@totalHours
                        asp-route-totalWorked=@totalHours.TotalWorkedHours
                        asp-route-totalOvertime=@totalHours.TotalOvertime
                        asp-route-totalSickness=@totalHours.TotalSickness
                        asp-route-totalVacation=@totalHours.TotalVacation
                        asp-route-totalHoliday=@totalHours.TotalHoliday
                        asp-route-totalTraining=@totalHours.TotalTraining
                        asp-route-totalOther=@totalHours.TotalOther>
                    Download als CSV
                </button>
                <div class="table-wrapper">
                    <table class="fl-table" align="center">
                        <thead>
                            <tr>
                                <th>Jaar</th>
                                <th>Maand</th>
                                <th>Uren gewerkt</th>
                                <th>Overwerk</th>
                                <th>Ziekte</th>
                                <th>Vakantie</th>
                                <th>Feestdagen</th>
                                <th>Training</th>
                                <th>Overig</th>
                            </tr>
                        <thead>

                            <tr class="notbold">
                                <td>
                                    @Html.DropDownList("totalhoursyear", yearsSelectList)
                                </td>
                                <td>
                                    @Html.DropDownList("totalhoursmonth", new SelectList(Enum.GetValues(typeof(Months))), "Alle maanden")
                                </td>
                                <td>@totalHours.TotalWorkedHours</td>
                                <td>@totalHours.TotalOvertime</td>
                                <td>@totalHours.TotalSickness</td>
                                <td>@totalHours.TotalVacation</td>
                                <td>@totalHours.TotalHoliday</td>
                                <td>@totalHours.TotalTraining</td>
                                <td>@totalHours.TotalOther</td>
                            </tr>

                    </table>
                </div>
            }
        </div>




        @* tabel 2*************************************************************************************************************** *@
        <div>
            <div align="center">
                <h1>Urenformulieren</h1>
            </div>
            @using (Html.BeginForm("Admin", "Admin"))
            {
        <input class="btn-primary btn btnposition" type="image" alt="filter toepassen" src="..\..\Images\Filter_Icon_White_Small.png" title="filter toepassen" />
                <div class="table-wrapper">
                    <table class="fl-table" align="center">
                        <thead>
                            <tr>
                                @*<th>
                                    Aangemaakt
                                    @{
                                        if (ViewBag.SortDate == stringAscending)
                                        {
                                            <button type="submit" class="btn-primary btn" asp-route-sortDate=@stringDescending><img src="..\..\Images\sortbyAscending.png" width="17"></button>
                                        }
                                        else
                                        {
                                            <button type="submit" class="btn-primary btn" asp-route-sortDate=@stringAscending><img src="..\..\Images\sortbyDescending.png" width="17"></button>
                                        }
                                    }
                                </th>*@
                                <th>
                                    Naam
                                    @Html.DropDownList("employeeName", new SelectList(employeeNames), "Geen filter")
                                </th>
                                <th>
                                    Jaar
                                    @Html.DropDownList("year", new SelectList(years), "Geen filter")
                                </th>
                                <th>
                                    Maand
                                    @Html.DropDownList("month", new SelectList(Enum.GetValues(typeof(Months))), "Geen filter")
                                </th>
                                <th>
                                    Goedgekeurd
                                    @Html.DropDownList("approved", new SelectList(new List<string> { "Goedgekeurd", "In Afwachting", "Afgekeurd"}), "Geen filter")
                                </th>
                                <th>
                                    Ingediend
                                    @Html.DropDownList("submitted", new SelectList(new List<string> { "Ingediend", "Niet ingediend" }), "Geen filter")
                                </th>
                                <th>Commentaar</th>
                                <th>Acties</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DeclarationFormModel declarationFormModel in Model)
                            {
                                <tr class="notbold">
                                    @*<td>@declarationFormModel.DateCreated.Day/@declarationFormModel.DateCreated.Month/@declarationFormModel.DateCreated.Year</td>*@
                                    <td>@declarationFormModel.EmployeeName</td>
                                    <td>@declarationFormModel.Year</td>
                                    <td>
                                        @{ 
                                            var maandInt = UrenRegistratieQien.GlobalClasses.MonthConverter.ConvertMonthToInt(declarationFormModel.Month);
                                            var maandString = UrenRegistratieQien.GlobalClasses.MonthConverter.ConvertIntToMaand(maandInt);
                                        }
                                        @maandString
                                    </td>
                                    <td>
                                        @if (declarationFormModel.Approved == "Approved")
                                        {
                                            <img class="center" title="Goedgekeurd" src="..\..\Images\Checkmark.png" style="margin: 0 auto; height: 15px; width: 25px" />
                                        }
                                        else if (declarationFormModel.Approved == "Rejected")
                                        {
                                            <img class="center" title="Afgekeurd" src="..\..\Images\xmark.png" style="margin: 0 auto; height: 15px; width: 15px" />
                                        }
                                        else if (declarationFormModel.Approved == "Pending")
                                        {
                                            <img class="center" title="In Afwachting" src="..\..\Images\Pending.jpg" style="margin: 0 auto; height: 25px; width: 25px" />
                                        }
                                    </td>
                                    <td>
                                        @if (declarationFormModel.Submitted == true)
                                        {
                                            <img class="center" title="Goedgekeurd" src="..\..\Images\Checkmark.png" style="margin: 0 auto; height: 15px; width: 25px" />
                                        }
                                        else
                                        {
                                            <img class="center" title="Afgekeurd" src="..\..\Images\xmark.png" style="margin: 0 auto; height: 15px; width: 15px" />
                                        }
                                    </td>
                                    <td>
                                        @if (declarationFormModel.Comment != null)
                                        {
                                            if (declarationFormModel.Comment.Length > 10)
                                            {
                                                
                                                string shortComment = (declarationFormModel.Comment.Substring(0, 10) + "...");
                                                
                                                @shortComment
                                            }
                                        }
                                    </td>
                                    <td>
                                        <select onchange="selectChanged(this);">
                                            <option value="">Kies je actie</option>
                                            <option value="@Url.Action("ViewDeclarationForm", "Admin", new { declarationFormModel.FormId })">Inzien</option>
                                            <option value="@Url.Action("DownloadExcel", "Download", new { declarationFormModel.FormId })">Download Excel</option>
                                            <option value="@Url.Action("DeleteDeclarationForm", "Admin", new { declarationFormModel.FormId })">Verwijderen</option>
                                            <option value="@Url.Action("ReopenForm", "Admin", new { declarationFormModel.FormId })">Heropenen</option>
                                        </select>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>

UrenRegistratieQien/Views/Admin/ChangeClient.cshtml
@model ClientModel

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">
        <form asp-controller="Admin" asp-action="EditClient">
            @Html.HiddenFor(m => m.ClientId)
            <table class="fl-table table-wrapper" align="center">
                <thead>
                    <tr>
                        <th>In database</th>
                        <th>Nieuw</th>
                    </tr>
                <thead>
                <tbody>
                    <tr>
                        <td>Bedrijfsnaam</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.CompanyName)</td>
                    </tr>
                    <tr>
                        <td>Algemeen telefoonnummer</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.CompanyPhone)</td>
                    </tr>
                    <tr>
                        <td>Naam 1e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact1Name)</td>
                    </tr>
                    <tr>
                        <td>Telefoonnummer 1e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact1Phone)</td>
                    </tr>
                    <tr>
                        <td>E-mailadres 1e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact1Email)</td>
                    </tr>
                    <tr>
                        <td>Naam 2e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact2Name)</td>
                    </tr>
                    <tr>
                        <td>Telefoonnummer 2e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact2Phone)</td>
                    </tr>
                    <tr>
                        <td>E-mailadres 2e contactpersoon</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Contact2Email)</td>
                    </tr>
                </tbody>
            </table>
            <button type="submit" class="btn-primary btn btnposition">Opslaan</button>
        </form>
    </div>
</div>

UrenRegistratieQien/Views/Admin/ChangeEmployee.cshtml
@model EditingEmployeeModel
@{ 
    var roleAsString = "";
    if(Model.Role == 1)
    {
        roleAsString = "Admin";
    }
    else if (Model.Role == 2)
    {
        roleAsString = "Medewerker";
    }
    else if(Model.Role == 3)
    {
        roleAsString = "Trainee";
    }
    else if (Model.Role == 4)
    {
        roleAsString = "Inactief";
    }

    //IEnumerable<string> clients = ViewBag.ListOfClients;

    var roleSelectList = new SelectList(new List<string> { "Admin", "Medewerker", "Trainee", "Inactief" });
    foreach(SelectListItem item in roleSelectList)
    {
        if(item.Text == roleAsString)
        {
            item.Selected = true;
        }
    }

}

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">
        <form asp-controller="Admin" asp-action="EditEmployee">
            @Html.HiddenFor(m => m.EmployeeId)
            @Html.HiddenFor(m => m.ClientId)
            <table class="fl-table table-wrapper" align="center">
                <thead>
                    <tr>
                        <th>In database</th>
                        <th>Nieuw</th>
                    </tr>
                <thead>

                <tbody>
                    <tr>
                        <td>Voornaam</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.FirstName)</td>
                    </tr>
                    <tr>
                        <td>Achternaam</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.LastName)</td>
                    </tr>
                    <tr>
                        <td>E-mail Adres</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Email)</td>
                    </tr>
                    <tr>
                        <td>Adres</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Address)</td>
                    </tr>
                    <tr>
                        <td>Telefoonnummer</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Phone)</td>
                    </tr>
                    <tr>
                        <td>Type medewerker</td>
                        <td class="notbold">
                            @Html.DropDownListFor(m => m.RoleAsString, roleSelectList)
                    </td>
                    </tr>
                    <tr>
                        <td>Opdrachtgever</td>
                        <td class="notbold">
                            @Html.DropDownListFor(m => m.ClientName, new SelectList(ViewBag.ListOfClients), Model.ClientName)
                        </td>
                    </tr>
                    <tr>
                        <td>Postcode</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.ZIPCode)</td>
                    </tr>
                    <tr>
                        <td>Woonplaats</td>
                        <td class="notbold">@Html.TextBoxFor(m => m.Residence)</td>
                    </tr>
                </tbody>
            </table>
        <button type="submit" class="btn-primary btn btnposition">Opslaan</button>
        </form>
    </div>
</div>

UrenRegistratieQien/Views/Admin/CreateFormForUser.cshtml
@model UrenRegistratieQien.Models.DeclarationFormModel

@{
    var lijst = ViewBag.Employees;
 }

    <div class="Container-1">

        <div class="box-1">
            @Html.Partial("_SideBoxAdmin")
        </div>


        <div align="center" class="box-2">
            <br />
            <br />
            <p><b>Maak hier een nieuw declaratieformulier aan voor een medewerker of trainee:</b></p>
            <br />
            <form asp-action="CreateFormForUser" asp-controller="Admin">
                <table align="center">
                    <tr>
                        <td>Naam medewerker</td>
                        <td>@Html.DropDownList("employeeId", lijst, "Selecteer naam", null)</td>
                    </tr>
                    <tr>
                        <td>Maand</td>
                        <td>@Html.DropDownList("month", new SelectList(Enum.GetValues(typeof(Months))), "Selecteer maand")</td>
                    </tr>
                    <tr>
                        <td>Jaar</td>
                        <td> <input asp-for="Year" type="number" value="@DateTime.Now.Year" min="1990" max="2100"> </td>
                    </tr>
                </table>
                <br />
                <br />
                <button type="submit" class="btn-primary btn">Toevoegen</button>
            </form>
        </div>
        
    </div>

UrenRegistratieQien/Views/Admin/SearchOverview.cshtml
@model List<EmployeeModel>

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">

        <div class="searchposition">

            @using (Html.BeginForm("SearchOverview", "Admin", FormMethod.Get))
            {
                @Html.TextBox("searchString")
                <input type="submit" value="Zoeken" class="btn-primary btn " />

            }
        </div>
        <table class="fl-table table-wrapper three" align="center">
            <thead>
                <tr>
                    <th class="textleft">Naam</th>
                    <th class="textleft">Type Medewerker</th>
                    <th class="textleft">Wijzig | Verwijder</th>
                </tr>
            <thead>

            <tbody>
                @foreach (var employee in Model)
                {
                    <tr>
                        <td class="notbold textleft">@employee.FirstName @employee.LastName</td>
                        <td class="notbold textleft">
                            @if (employee.Role == 1)
                            {
                                <text>Admin</text>
                            }
                            else if (employee.Role == 2)
                            {
                                <text>Medewerker</text>
                            }
                            else if (employee.Role == 3)
                            {
                                <text>Trainee</text>
                            }
                            else if (employee.Role == 4)
                            {
                                <text>Inactief</text>
                            }
                        </td>
                        <td class="notbold textleft">
                            <a asp-area=""
                               asp-controller="Admin"
                               asp-action="ChangeEmployee"
                               asp-route-EmployeeId="@employee.EmployeeId">
                                Wijzig
                            </a>
                            |
                            @Html.ActionLink("Verwijder", "DeleteEmployee", new { EmployeeId = employee.EmployeeId }, new { onclick = "return confirm('Weet je zeker dat je de medewerker wilt verwijderen?');" })

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

UrenRegistratieQien/Views/Admin/ShowClients.cshtml
@model List<ClientModel>

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">
        <table class="fl-table table-wrapper three">
            <thead>
                <tr>
                    <th class="textleft">Naam opdrachtgever</th>
                    <th class="textleft">Wijzig | Verwijder</th>
                </tr>
            <thead>

            <tbody>
                @foreach (var client in Model)
                {
                    <tr>
                        <td class="textleft notbold">@client.CompanyName</td>
                        <td class="textleft notbold">
                            <a asp-area=""
                               asp-controller="Admin"
                               asp-action="ChangeClient"
                               asp-route-ClientId="@client.ClientId">
                                Wijzig
                            </a>
                            |
                            @Html.ActionLink("Verwijder", "DeleteClient", new { ClientId = client.ClientId }, new { onclick = "return confirm('Weet je zeker dat je de opdrachtgever wilt verwijderen?');" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

UrenRegistratieQien/Views/Admin/ViewDeclarationForm.cshtml
@model DeclarationFormModel
@{
    ViewData["Title"] = "ViewDeclarationForm";
    int i = 0;
}

<div class="Container-1">
    <div class="box-1">
        @Html.Partial("_SideBoxAdmin")
    </div>

    <div class="box-2">
        <form>
            <a class="btnposition" asp-area=""
               asp-controller="Download"
               asp-action="DownloadExcel"
               asp-route-formId="@Model.FormId">
                Download Excel
            </a>
        </form>
        <form>
            <a class="btnposition" asp-area=""
               asp-controller="Download"
               asp-action="DownloadAttachments"
               asp-route-formId="@Model.FormId">
                Download Bijlagen
            </a>
        </form>
        <div>
            @if (Model.Comment != null)
            {
                string commentaarString = "Rede voor afkeuring: " + Model.Comment;
                @commentaarString

            }
        </div>

        <table align="center" class="fl-table table-wrapper">
            <thead>
                <tr>
                    <th>Datum</th>
                    <th>Gewerkt</th>
                    <th>Overwerk</th>
                    <th>Ziekte</th>
                    <th>Vakantie</th>
                    <th>Feestdagen</th>
                    <th>Training</th>
                    <th>Overig</th>
                    <th>Overig Uitleg</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var hourRow in Model.HourRows)
                {

                    if (i == 15)
                    {

                    <thead>
                        <tr>
                            <th class="tableHeader">Date</th>
                            <th class="tableHeader">Gewerkt</th>
                            <th class="tableHeader">Overwerk</th>
                            <th class="tableHeader">Ziekte</th>
                            <th class="tableHeader">Vakantie</th>
                            <th class="tableHeader">Feestdagen</th>
                            <th class="tableHeader">Training</th>
                            <th class="tableHeader">Overig</th>
                            <th>Overig Uitleg</th>
                        </tr>
                    </thead>
                }
                i += 1;

                <tr class="notbold">
                    <td>@hourRow.Date</td>
                    <td>@hourRow.Worked</td>
                    <td>@hourRow.Overtime</td>
                    <td>@hourRow.Sickness</td>
                    <td>@hourRow.Vacation</td>
                    <td>@hourRow.Holiday</td>
                    <td>@hourRow.Training</td>
                    <td>@hourRow.Other</td>
                    <td>@hourRow.OtherExplanation</td>
                </tr>
            }
                </tbody>
            </table>
        </div>
</div>